[web]
app ansible_host=i-07a54863b39a8186c 

[web:vars]
ansible_connection=amazon.aws.aws_ssm
ansible_aws_ssm_region=ap-south-1
ansible_aws_ssm_bucket_name=devops-mini-ansible-ssm-998230060743
ansible_python_interpreter=/usr/bin/python3
